weather_transform:
  outputs:
    dev:
      dataset: weather_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\danie\Downloads\weather-pipeline\service-account.json
      location: US
      method: service-account
      priority: interactive
      project: weather-pipeline-486804
      threads: 1
      type: bigquery
  target: dev