weather_transform:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: weather-pipeline-486804
      dataset: weather_data
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      # THE MAGIC LINE: Read the environment variable instead of a hardcoded path
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"